import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import NavBar from "~/components/NavBar";
import Footer from "~/components/Footer";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({
    text: "from tRPC. This is a trpc query calling on hello method of post model.",
  });

  return (
    <>
      <Head>
        <title>Trustworthi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ffffff] to-[#808080]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Trust<span className="text-[hsl(0,59%,33%)]">worth</span>i
          </h1>
          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row sm:justify-center md:gap-8">
            <div className="text-center text-lg">
              Insure your estate with state-of-the-art home inventory app, Trust
              <span className="text-[hsl(0,59%,33%)]">worth</span>i
            </div>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
